apiVersion: 1

datasources:
  - name: MariaDB
    type: mysql
    access: proxy
    url: db:3306
    database: finanzen
    user: finanzen
    secureJsonData:
      password: 'change_me_secure_password'
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    editable: true
