apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    database: finanzen
    user: finanzen
    secureJsonData:
      password: 'change_me_secure_password'
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1600
      timescaledb: false
    editable: true
