# Kategorien für Transaktionen
categories:
  income:
    - "Gehalt"
    - "Bonus"
    - "Miete Sonnenberg"
    - "Miete Neuhof"
    - "Sonstiges Einkommen"
  
  expenses:
    # Alte Schreibweise (funktioniert weiterhin)
    - "Lebensmittel"
    
    # Neue hierarchische Schreibweise
    - name: "Wohnen"
      subcategories:
        - "Miete"
        - "Strom"
        - "Internet"
        
    - name: "Mobilität"
      children:  # 'children' oder 'subcategories' geht beides
        - "Tanken"
        - "Versicherung"
        - "Wartung"
